Fashion/Models/Article.cs
namespace Fashion.Models
{
    /// <summary>
    /// The class article
    /// </summary>
    public class Article
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        public int ID { get; set; }

        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        /// <value>
        /// The title.
        /// </value>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the content.
        /// </summary>
        /// <value>
        /// The content.
        /// </value>
        public string Content { get; set; }

        /// <summary>
        /// Gets or sets the image.
        /// </summary>
        /// <value>
        /// The image.
        /// </value>
        public string Image { get; set; }
    }
}

Fashion/Models/ListProduct.cs
using System.Collections.Generic;

namespace Fashion.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class ListProduct
    {
        /// <summary>
        /// Gets or sets the products.
        /// </summary>
        /// <value>
        /// The products.
        /// </value>
        public List<Product> Products { get; set; }

        /// <summary>
        /// Gets or sets the page information.
        /// </summary>
        /// <value>
        /// The page information.
        /// </value>
        public PageInformation PageInformation { get; set; }
    }
}

Fashion/Models/PageInformation.cs
namespace Fashion.Models
{
    /// <summary>
    /// Page information
    /// </summary>
    public class PageInformation
    {
        /// <summary>
        /// Gets or sets the current page.
        /// </summary>
        /// <value>
        /// The current page.
        /// </value>
        public int CurrentPage { get; set; }

        /// <summary>
        /// Gets or sets the total page.
        /// </summary>
        /// <value>
        /// The total page.
        /// </value>
        public int TotalPage { get { return TotalRecord % PageSize != 0 ? ((TotalRecord / PageSize) + 1) : (TotalRecord / PageSize); } }

        /// <summary>
        /// Gets or sets the total record.
        /// </summary>
        /// <value>
        /// The total record.
        /// </value>
        public int TotalRecord { get; set; }

        /// <summary>
        /// Gets or sets the size of the page.
        /// </summary>
        /// <value>
        /// The size of the page.
        /// </value>
        public int PageSize { get; set; }
    }
}

Fashion/Models/Product.cs
namespace Fashion.Models
{
    /// <summary>
    /// Product model
    /// </summary>
    public class Product
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        public int ID { get; set; }
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        public string Name { get; set; }
        /// <summary>
        /// Gets or sets the desciption.
        /// </summary>
        /// <value>
        /// The desciption.
        /// </value>
        public string Desciption { get; set; }
        /// <summary>
        /// Gets or sets the quatity.
        /// </summary>
        /// <value>
        /// The quatity.
        /// </value>
        public int Quatity { get; set; }
        /// <summary>
        /// Gets or sets the price.
        /// </summary>
        /// <value>
        /// The price.
        /// </value>
        public decimal Price { get; set; }

        /// <summary>
        /// Gets or sets the image.
        /// </summary>
        /// <value>
        /// The image.
        /// </value>
        public string Image { get; set; }

        /// <summary>
        /// Gets or sets the URL.
        /// </summary>
        /// <value>
        /// The URL.
        /// </value>
        public string Url { get; set; }
    }
}

Fashion/Controllers/ArticleSurfaceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Examine;
using Fashion.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using umbraco;

namespace Fashion.Controllers
{
    public class ArticleSurfaceController : SurfaceController
    {
        private const int PageSize = 2;

        public ActionResult GetArticleByCategory(int id)
        {
            //var search = ExamineManager.Instance.SearchProviderCollection["ArticleSearcher"];
            //var searchCriteria = search.CreateSearchCriteria();
            //var query = searchCriteria.Field("titleArticle", "Jodie").Compile();
            //var result = search.Search("LP", true);

            //var a = result.Count();

            //var search = ExamineManager.Instance.SearchProviderCollection["WebsiteSearcher"];
            ////var searchCriteria = search.CreateSearchCriteria();
            ////var query = searchCriteria.Field("titleArticle", "Jodie").Compile();
            //var result = search.Search("LP", true);

            //var a = result.Count();


            var articles = uQuery.GetNodesByType("Article");


            return PartialView("_ArticleDetails", articles.Where(x => x.Parent.Id == id));
        }

        public ActionResult ListProduct(int page = 1, string sortType = "ASC")
        {
            var products = uQuery.GetNodesByType("Product");

            List<Product> listProduct = products.Select(product => new Product
                {
                    Desciption = product.GetProperty<string>("descriptionProduct"), 
                    Name = product.GetProperty<string>("nameProduct"), 
                    Image = product.GetProperty<string>("imageProduct"), 
                    Url = product.Url
                }).ToList();

            var pagingInformation = new PageInformation
                {
                    CurrentPage = 0,
                    PageSize = 56,
                    TotalRecord = listProduct.Count
                };

            var productWrap = new ListProduct
                {
                    Products = listProduct.OrderByDescending(x => x.Name).Skip((page - 1) * PageSize).Take(PageSize).ToList(), 
                    PageInformation = pagingInformation
                };

            return PartialView("AllProducts", productWrap);
        }

        [HttpPost]
        public ActionResult Search(string txtSearch)
        {
            var search = ExamineManager.Instance.SearchProviderCollection["ArticleSearcher"];
            var result = search.Search(txtSearch, true);

            List<Article> articles = new List<Article>();
            foreach (var searchResult in result)
            {
                articles.Add(new Article
                    {
                        ID = searchResult.Id,
                        Title = searchResult.Fields["titleArticle"]
                    });
            }

            return View("SearchResult", articles);
        }
    }
}

Fashion/Views/Article.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<!-- Generic -->
<article class="container box style3">
    <header>
        <h1>@Umbraco.Field("titleArticle")</h1>
    </header>
    <div style="text-align: center">
        <img src="@Umbraco.Field("imageArticle")" width="200" height="200"/>
    </div>
    @Umbraco.Field("contentArticle")
    <span style="float: right; font-weight: bold">@Umbraco.Field("authorArticle")</span>
</article>

Fashion/Views/ArticleSurface/AllProducts.cshtml
@model Fashion.Models.ListProduct
<!-- Generic -->
<article class="container box style3">
    <header>
        <h1>List Product</h1>
        <div class="float-right">
            <select id="sortType">
                <option value="DESC">DESC</option>
                <option value="ASC">ASC</option>
            </select>
        </div>
    </header>
    <div>
        @foreach (var product in Model.Products)
        {
            <div style="width: 30%; float: left;">
                <span>@product.Name</span><br/>
                <a href="@product.Url"><img src="~/ImageGen.ashx?image=@product.Image&AllowUpSizing=true&width=200"/></a>
            </div>
        }
    </div>
   
</article>

 <div class="pagination">
			<ul>
			@*@Html.Partial("_Paging", Model.PageInformation)*@
			</ul>
			</div>
<br class="clr"/>
</div>

    <script type="text/javascript">
        $(document).ready(function() {
            $(".pagination li a").click(function () {
                var sortType = $("#sortType").val();
                var page = $(this).attr("data-page");
                
                if (page) {
                    getAllProducts(page, sortType);
                }
            });
            $("#sortType").change(function() {
                var type = $(this).val();
                var currentPage = 1;

                getAllProducts(currentPage, type);


            });
        });
        
        function getAllProducts(page, sortType) {
            $.ajax({
                url: '@Url.Action("ListProduct", "ArticleSurface")',
                type: "GET",
                data: { page: page, sortType:sortType },
                success: function (response) {
                    $(".span9").html(response);
                }
            });
        }
    </script>

Fashion/Views/ArticleSurface/SearchResult.cshtml
@model List<Fashion.Models.Article>

@{
    ViewBag.Title = "Search result";
    Layout = "../Master.cshtml";
}

<h2>Search result</h2>

@foreach (var item in Model)
{
    <div>@item.ID</div><br/>
    <div>@item.Title</div>
}

Fashion/Views/ArticleSurface/_ArticleDetails.cshtml
@model IEnumerable<umbraco.NodeFactory.Node>

@{
    <ul>
        @foreach (var content in Model)
        {
            <li><a href="@content.Url">@content.Name</a></li>
        }
    </ul>
}

Fashion/Views/ArticleSurface/_Paging.cshtml
@model Fashion.Models.PageInformation


@if (Model.CurrentPage > 1)
{
    <li><a href="#" data-page="1">&lsaquo;</a></li>
}
else
{
    <li><a href="#">&lsaquo;</a></li>
}

@for (int i = 1; i <= Model.TotalPage; i++)
{
    if (Model.CurrentPage == i)
    {
    <li><a href="#">@i</a></li>
    }
    else
    {
    <li><a href="#" data-page="@i">@i</a></li>
    }
}

@if (Model.CurrentPage < Model.TotalPage)
{
    <li><a href="#" data-page="@{
                                   int i = Model.CurrentPage + 1;
                               }@i">&rsaquo;</a></li>
}
else
{
    <li><a href="#">&rsaquo;</a></li>
}

Fashion/Views/Category.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

Fashion/Views/Master.cshtml
@using System.Web.Optimization
@inherits UmbracoTemplatePage
@{
    Layout = null;
}
<!DOCTYPE HTML>
<!--
    Overflow 1.0 by HTML5 UP
    html5up.net | twitter.com/n33co
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
    -->
<html>
<head>
    <title>@Umbraco.Field("pageName") | @Umbraco.Field("siteName", recursive: true)</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    @*@Styles.Render("~/Css")*@
    <link href="~/Content/assets/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/assets/css/docs.css" rel="stylesheet" />
    <link href="~/Content/assets/style.css" rel="stylesheet" />
    <link href="~/Content/assets/js/google-code-prettify/prettify.css" rel="stylesheet" />
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic" rel="stylesheet" type="text/css" />
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="~/Content/assets/js/jquery.js"></script>
	<script src="~/Content/assets/js/google-code-prettify/prettify.js"></script>
    <script src="~/Content/assets/js/application.js"></script>
    <script src="~/Content/assets/js/bootstrap-transition.js"></script>
    <script src="~/Content/assets/js/bootstrap-modal.js"></script>
    <script src="~/Content/assets/js/bootstrap-scrollspy.js"></script>
    <script src="~/Content/assets/js/bootstrap-alert.js"></script>
    <script src="~/Content/assets/js/bootstrap-dropdown.js"></script>
    <script src="~/Content/assets/js/bootstrap-tab.js"></script>
    <script src="~/Content/assets/js/bootstrap-tooltip.js"></script>
    <script src="~/Content/assets/js/bootstrap-popover.js"></script>
    <script src="~/Content/assets/js/bootstrap-button.js"></script>
    <script src="~/Content/assets/js/bootstrap-collapse.js"></script>
    <script src="~/Content/assets/js/bootstrap-carousel.js"></script>
    <script src="~/Content/assets/js/bootstrap-typeahead.js"></script>
    <script src="~/Content/assets/js/bootstrap-affix.js"></script>
    <script src="~/Content/assets/js/jquery.lightbox-0.5.js"></script>
	<script src="~/Content/assets/js/bootsshoptgl.js"></script>
	 <script type="text/javascript">
	     $(function () {
	         $('#gallery a').lightBox();
	     });
    </script>
    @RenderSection("scripts", false)

</head>
<body>

    <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                @*<a id="logoM" href="index.html">
                    <img src="~/Content/assets/img/logo.png" alt="Bootsshop" /></a>*@
                <a data-target="#sidebar" data-toggle="collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class=""><a href="index.html">Home	</a></li>
                        <li class=""><a href="special_offer.html">Specials Offer</a></li>
                        <li class=""><a href="normal.html">Delivery</a></li>
                        <li class=""><a href="contact.html">Contact</a></li>
                    </ul>
                    @using (Html.BeginForm("Search", "ArticleSurface"))
                    {
                        <input id="txtSearch" name="txtSearch" type="text" placeholder="Enter text search" class="search-query span5" />
                    }
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Login <b class="caret"></b></a>
                            <div class="dropdown-menu">
                                <form class="form-horizontal loginFrm">
                                    <div class="control-group">
                                        <input type="text" class="span2" id="inputEmail" placeholder="Email">
                                    </div>
                                    <div class="control-group">
                                        <input type="password" class="span2" id="inputPassword" placeholder="Password">
                                    </div>
                                    <div class="control-group">
                                        <label class="checkbox">
                                            <input type="checkbox">
                                            Remember me
                                        </label>
                                        <button type="submit" class="btn btn-block">Sign in</button>
                                    </div>
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- /.nav-collapse -->
            </div>
        </div>
        <!-- /navbar-inner -->
    </div>
    <!-- ======================================================================================================================== -->
    <div id="mainBody" class="container">
        <header id="header">
            <div class="row">
                <div class="span12">
                    <a href="index.html">
                        <img src="~/Content/assets/img/logo.png" alt="Bootsshop" /></a>

                    <div class="pull-right">
                        <br />
                        <a href="product_summary.html"><span class="btn btn-mini btn-warning"><i class="icon-shopping-cart icon-white"></i>[ 3 ] </span></a>
                        <a href="product_summary.html"><span class="btn btn-mini active">$155.00</span></a>
                        <span class="btn btn-mini">&pound;</span>
                        <span class="btn btn-mini">&euro;</span>
                    </div>
                </div>
            </div>
            <div class="clr"></div>
        </header>
        <!-- ==================================================Header End====================================================================== -->
    

    <div class="row">
        <div id="sidebar" class="span3">
            @Html.Partial("umbNavigate")
        </div>
        <div class="span9">
            <ul class="breadcrumb">
		        <li><a href="index.html">Home</a> <span class="divider">/</span></li>
		        <li class="active">Products Name</li>
            </ul>

            @RenderBody()
        </div>
    </div>

    <!-- Footer ------------------------------------------------------ -->
<hr class="soft">
<div  id="footerSection">
	<div class="row">
		<div class="span3">
			<h5>ACCOUNT</h6>
			<a href="login.html">YOUR ACCOUNT</a>
			<a href="login.html">PERSONAL INFORMATION</a> 
			<a href="login.html">ADDRESSES</a> 
			<a href="login.html">DISCOUNT</a>  
			<a href="login.html">ORDER HISTORY</a>
		 </div>
		<div class="span3">
			<h5>INFORMATION</h5>
			<a href="contact.html">CONTACT</a>  
			<a href="register.html">REGISTRATION</a>  
			<a href="legal_notice.html">LEGAL NOTICE</a>  
			<a href="tac.html">TERMS AND CONDITIONS</a> 
			<a href="faq.html">FAQ</a>
		 </div>
		<div class="span3">
			<h5>OUR OFFERS</h5>
			<a href="#">NEW PRODUCTS</a> 
			<a href="#">TOP SELLERS</a>  
			<a href="special_offer.html">SPECIAL OFFERS</a>  
			<a href="#">MANUFACTURERS</a> 
			<a href="#">SUPPLIERS</a> 
		 </div>
		<div id="socialMedia" class="span3 pull-right">
			<h5>SOCIAL MEDIA </h5>
			<a href="#"><img width="60" src="~/Content/assets/img/facebook.png" title="facebook"/></a>
			<a href="#"><img width="60" src="~/Content/assets/img/twitter.png" title="twitter"/></a>
			<a href="#"><img width="60" src="~/Content/assets/img/rss.png" title="rss"/></a>
			<a href="#"><img width="60" src="~/Content/assets/img/youtube.png" title="youtube"/></a>
		 </div> 
	 </div>
	 <hr class="soft">
	<p class="pull-right">&copy; Boot'sshop</p>
</div>

    </div><!-- /container -->
    
    
    
</body>

</html>

Fashion/Views/News.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

Fashion/Views/Overflow.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@{ Html.RenderAction("ListProduct", "ArticleSurface"); }

Fashion/Views/Partials/umbBanner.cshtml
@inherits UmbracoTemplatePage

@if (CurrentPage.HideBanner == false)
{
    <!-- Banner -->
	<section id="banner">
		<header>
			<h2>@Umbraco.Field("bannerHeader")</h2>
		</header>
		@Umbraco.Field("bannerText")
		<footer>
			<a href="#first" class="button style2 scrolly">@Umbraco.Field("bannerLinkText")</a>
		</footer>
	</section>
}

Fashion/Views/Partials/umbContact.cshtml
@inherits UmbracoTemplatePage
@*
    The contact form is handled through javascript
    See /Scripts/Overflow.js for the AJAX post
*@

<!-- Contact -->
<article class="container box style3">
    <header>
        <h2>@CurrentPage.Title</h2>
        <p>@CurrentPage.SubTitle</p>
        <p class="sending-message">Sending your message...</p>
        <p class="success-message">Thanks! we'll get back to you soon.</p>
        <p class="error-message"></p>
    </header>
    <form>
        <div class="row half">
            <div class="6u"><input type="text" class="text" name="name" placeholder="Name" /></div>
            <div class="6u"><input type="text" class="text" name="email" placeholder="Email" /></div>
        </div>
        <div class="row half">
            <div class="12u">
                <textarea name="message" placeholder="Message"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="12u">
                <ul class="actions">
                    <li><a href="" class="button form" rel="nofollow">Send Message</a></li>
                </ul>
            </div>
        </div>
        <input type="hidden" name="settingsNodeId" value="@CurrentPage.Id" />
    </form>
</article>

Fashion/Views/Partials/umbFeature.cshtml
@inherits UmbracoTemplatePage
@*
    This partial is using a concept called IsHelpers:
    - IsFirst() determines if the node we're  rendering is the first in the list of nodes.
      If IsFirst() is true we add id="first" to the <article> element, else we don't specify
      an id on the article element at all (by specifying a null).

    - IsEven() determines if the page count is even or odd, so for the first node IsEven() 
      is false, for the second node IsEven() is true, etc.
      If IsEven() is true, we add "right" to the classes on the article element, when it's 
      false, we add "left" instead. This way, if there's multiple features, the text flips 
      between left and right for each one of them, giving a nice effect on the page.
    
    Since the FeatureHeader and FeatureText properties are simple text, we need to replace
    linebreaks with a "<br />" and since Razor tries to help you be safe, it doesn't allow 
    direct output of the HTML here, so that's where we need to force it by using Html.Raw.
*@
<article id="@(CurrentPage.IsFirst() ? "first" : null)" class="container box style1 @(CurrentPage.IsEven() ? "right" : "left")">
    <a href="@CurrentPage.Image" class="image full"><img src="@CurrentPage.Image" alt="" /></a>
    <div class="inner">
        <header>
            <h2>
                @Html.Raw(Umbraco.ReplaceLineBreaksForHtml(CurrentPage.FeatureHeader))
            </h2>
        </header>
        @Html.Raw(Umbraco.ReplaceLineBreaksForHtml(CurrentPage.FeatureText))
    </div>
</article>

Fashion/Views/Partials/umbNavigate.cshtml
@inherits UmbracoTemplatePage

@{
    Layout = null;

    var menuItems = uQuery.GetNodesByType("Category");
    
    <ul class="nav nav-list bs-docs-sidenav" style="display: block;">
        @foreach (var menuItem in menuItems)
        {
            <li class="subMenu"><a>@menuItem.Name</a>
                @Html.Action("GetArticleByCategory", "ArticleSurface", new {id = @menuItem.Id})
            </li>
        }
        <li class="subMenu">
            <a id="product" href="#">View Products</a>
        </li>
        </ul>
}

<script type="text/javascript">
    $(document).ready(function() {
        $("#product").click(function() {
            $.ajax({
                url: '@Url.Action("ListProduct", "ArticleSurface")',
                type: "GET",
                success: function(response) {
                    $(".span9").html(response);
                }
            });
        });
    });
</script>

Fashion/Views/Partials/umbSocial.cshtml
@inherits UmbracoTemplatePage
@{
    // Model.Content is the current page that we're on
    // AncestorsOrSelf is all of the ancestors this page has in the tree
    // (1) means: go up to level 1 and stop looking for more ancestors when you get there
    // First() gets the first ancestor found (the home page, on level 1).
    var homePage = CurrentPage.AncestorsOrSelf(1).First();
}

<ul class="icons">
    @RenderLinkIfNotEmpty(homePage.TwitterLink, "twitter", "Twitter")
    @RenderLinkIfNotEmpty(homePage.FacebookLink, "facebook", "Facebook")
    @RenderLinkIfNotEmpty(homePage.GoogleLink, "google-plus", "Google+")
    @RenderLinkIfNotEmpty(homePage.PinterestLink, "pinterest", "Pinterest")
    @RenderLinkIfNotEmpty(homePage.DribbbleLink, "dribbble", "Dribbble")
    @RenderLinkIfNotEmpty(homePage.LinkedinLink, "linkedin", "LinkedIn")
</ul>

@helper RenderLinkIfNotEmpty(dynamic link, string cssClass, string linkName)
{
    // A helper function is handy when you have to do the same thing over and over again
    // So now we only have to write the "if" check and list item once, and we only need
    // to put in the things that can vary: the link, the cssClass and the linkName.
    
    if (string.IsNullOrEmpty(link) == false)
    {
        <li><a href="@link" class="icon icon-@cssClass solo"><span>@linkName</span></a></li>
    }
}

Fashion/Views/Partials/umbTextPage.cshtml
@inherits UmbracoTemplatePage

<!-- Generic -->
<article class="container box style3">
    <header>
        <h2>@CurrentPage.Title</h2>
        <p>@CurrentPage.SubTitle</p>
    </header>
    @CurrentPage.BodyText
</article>

Fashion/Views/Product.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    Layout = "Master.cshtml";
}

Fashion/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>